# Generated by Django 6.0.5 on 2026-05-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_inventoryitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
